import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { createServiceClient } from "@/lib/supabase/server";
import { logActivity } from "@/lib/activity";
import { RECRUITER_COOKIE } from "@/lib/constants";

const INK = rgb(0.11, 0.13, 0.15);
const MUTED = rgb(0.36, 0.39, 0.44);
const BRASS = rgb(0.78, 0.61, 0.24);
const MARGIN = 50;
const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;

function wrapText(text: string, font: import("pdf-lib").PDFFont, size: number, maxWidth: number) {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const trial = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(trial, size) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = trial;
    }
  }
  if (current) lines.push(current);
  return lines;
}

async function buildPdf(talent: {
  full_name: string;
  email: string;
  phone: string | null;
  country: string;
  city: string | null;
  one_liner: string;
  bio: string | null;
  skill_tags: string[];
  portfolio_url: string | null;
  linkedin_url: string | null;
  showcase_score: number | null;
}) {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_W, PAGE_H]);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let y = PAGE_H - MARGIN;
  const contentWidth = PAGE_W - MARGIN * 2;

  page.drawText("ALX ProConnect", { x: MARGIN, y, size: 14, font: bold, color: BRASS });
  y -= 34;

  page.drawText(talent.full_name, { x: MARGIN, y, size: 22, font: bold, color: INK });
  y -= 20;

  const metaLine = [
    [talent.city, talent.country].filter(Boolean).join(", "),
    talent.showcase_score ? `Showcase score ${talent.showcase_score.toFixed(1)}/5` : null,
  ]
    .filter(Boolean)
    .join("   ·   ");
  page.drawText(metaLine, { x: MARGIN, y, size: 10, font: regular, color: MUTED });
  y -= 26;

  for (const line of wrapText(talent.one_liner, regular, 12, contentWidth)) {
    page.drawText(line, { x: MARGIN, y, size: 12, font: regular, color: INK });
    y -= 16;
  }
  y -= 10;

  if (talent.bio) {
    page.drawText("ABOUT", { x: MARGIN, y, size: 9, font: bold, color: MUTED });
    y -= 16;
    for (const line of wrapText(talent.bio, regular, 11, contentWidth)) {
      page.drawText(line, { x: MARGIN, y, size: 11, font: regular, color: INK });
      y -= 15;
    }
    y -= 8;
  }

  if (talent.skill_tags.length > 0) {
    page.drawText("SKILLS", { x: MARGIN, y, size: 9, font: bold, color: MUTED });
    y -= 16;
    for (const line of wrapText(talent.skill_tags.join("   •   "), regular, 10, contentWidth)) {
      page.drawText(line, { x: MARGIN, y, size: 10, font: regular, color: INK });
      y -= 14;
    }
    y -= 8;
  }

  page.drawText("CONTACT", { x: MARGIN, y, size: 9, font: bold, color: MUTED });
  y -= 16;

  const contactRows: [string, string][] = [["Email", talent.email]];
  if (talent.phone) contactRows.push(["Phone", talent.phone]);
  if (talent.portfolio_url) contactRows.push(["Portfolio", talent.portfolio_url]);
  if (talent.linkedin_url) contactRows.push(["LinkedIn", talent.linkedin_url]);

  for (const [label, value] of contactRows) {
    page.drawText(label, { x: MARGIN, y, size: 10, font: bold, color: MUTED });
    page.drawText(value, { x: MARGIN + 70, y, size: 10, font: regular, color: INK });
    y -= 15;
  }

  page.drawText(
    "Generated by ALX ProConnect · Please use this contact information for recruitment purposes only.",
    { x: MARGIN, y: 30, size: 8, font: regular, color: MUTED }
  );

  return doc.save();
}

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const cookieStore = await cookies();
  const recruiterId = cookieStore.get(RECRUITER_COOKIE)?.value;

  if (!recruiterId) {
    return NextResponse.json({ error: "Please enter your email first." }, { status: 401 });
  }

  const supabase = createServiceClient();

  const [{ data: recruiter }, { data: talent }] = await Promise.all([
    supabase.from("recruiters").select("id, work_email").eq("id", recruiterId).maybeSingle(),
    supabase
      .from("talents")
      .select(
        "full_name, email, phone, country, city, one_liner, bio, skill_tags, portfolio_url, linkedin_url, showcase_score"
      )
      .eq("id", id)
      .eq("status", "published")
      .maybeSingle(),
  ]);

  if (!recruiter) {
    return NextResponse.json({ error: "Please enter your email again." }, { status: 401 });
  }
  if (!talent) {
    return NextResponse.json({ error: "Profile not found." }, { status: 404 });
  }

  await logActivity({
    actorType: "recruiter",
    actorEmail: recruiter.work_email,
    action: "profile_downloaded",
    metadata: { talent_id: id },
  });

  const bytes = await buildPdf(talent);

  return new NextResponse(new Uint8Array(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${talent.full_name.replace(/\s+/g, "-")}-ALX-ProConnect.pdf"`,
    },
  });
}
